str_length = input ("Enter the length of the room\n")
str_width = input ("Enter the width of the room\n")
length = float(str_length)
width = float(str_width)
area = float(length * width)
print (area)
meter = input ("How much for 1 meter\n")
meter = float (meter)
price = float (area * meter)
print (price)